function goToAttendance() {
    window.location.href = "https://campus.srmcem.ac.in/psp/ps/EMPLOYEE/HRMS/c/MANAGE_ACADEMIC_RECORDS.STDNT_ATTEND_TERM.GBL?PORTALPARAM_PTCNAV=HC_STDNT_ATTENDANCE_GBL&EOPP.SCNode=HRMS&EOPP.SCPortal=EMPLOYEE&EOPP.SCName=HCSR_CURRICULUM_MANAGEMENT&EOPP.SCLabel=Curriculum%20Management&EOPP.SCPTfname=HCSR_CURRICULUM_MANAGEMENT&FolderPath=PORTAL_ROOT_OBJECT.HCSR_CURRICULUM_MANAGEMENT.HCSR_ATTENDANCE_ROSTER.HC_STDNT_ATTENDANCE_GBL&IsFolder=false"; 
}

function goToAssignment() {
    window.location.href = "https://campus.srmcem.ac.in/psp/ps/EMPLOYEE/HRMS/c/SA_LEARNER_SERVICES.SS_LAM_STD_GR_LST.GBL?PORTALPARAM_PTCNAV=HC_SS_LAM_STD_GR_LST_GBL1&EOPP.SCNode=HRMS&EOPP.SCPortal=EMPLOYEE&EOPP.SCName=CO_EMPLOYEE_SELF_SERVICE&EOPP.SCLabel=Self%20Service&EOPP.SCPTfname=CO_EMPLOYEE_SELF_SERVICE&FolderPath=PORTAL_ROOT_OBJECT.CO_EMPLOYEE_SELF_SERVICE.HCCC_ENROLLMENT.HC_SS_LAM_STD_GR_LST_GBL1&IsFolder=false"; 
}
